FROM node:19.6.0 AS build

# Rest of the Dockerfile remains the same
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:19.6.0-slim
WORKDIR /app
COPY --from=build /app/build ./build


CMD ["npm", "start"]
