# Use an official Node.js runtime as the base image
FROM node:19.6.0 AS build

# Set the working directory inside the container .
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React app
RUN npm run build

# Use a lightweight Node.js runtime as the final base image
FROM node:19.6.0-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the build files from the previous stage to the working directory
COPY --from=build /app/build ./build

# Expose the port that the application will run on
EXPOSE 80

# Start the React app
CMD ["npm", "start"]
